### ISSUE TITLE
Add Roboto-Regular font for Hebrew Script.

### ISSUE THREAD

**Issue by dhead666** [BigNoid/Aeon-Nox#602]
If I understand correctly the default font is MC360 which doesn't got Hebrew script.

The current state of the addon is that one should change the font to Ubuntu in order for Hebrew script text to show correctly.
This is a partial solution because of the following:
- When changing the font to Ubuntu the BebasNeue font is used additionally for the menus (which isn't the case for when using default font), and BebasNeue doesn't got Hebrew script so the user need to manually replace BebasNeue.ttf with Ubuntu-C.ttf, additional work that isn't easy for many users especially on Linux based OpenELEC and etc.
- When replacing BebasNeue.ttf with Ubuntu-C.ttf the menus looks bad and Ubuntu-C isn't much pretty.

Anyway I've replace MC360.ttf with Roboto-Regular.ttf and it looks absolutely great for both Hebrew and English scripts, menus and subtitles.

I've tested few free fonts and this was the best and it worked as a replacement for MC360.ttf, meaning the same font size and etc (if these are different for the fonts) so please add the font with the same configuration as MC360.ttf.

The official Roboto Google's release doesn't got Hebrew script (if I'm not mistaken) so the version that I've used is from uNiversal WIP Roboto Fonts (Hebrew test folder) at 
http://forum.xbmc.org/showthread.php?tid=150067

Thanks is advance.

**Comment by freak4pc** [comment]
Sorry for bumping this extremely old topic but this doesn't seem solved as of this point...
Anything that can be done ? 
![img_1566](https://cloud.githubusercontent.com/assets/605076/9329894/22e70740-45be-11e5-8345-b09a4856469f.JPG)

**Comment by BigNoid** [comment]
Yes, you would need a font that supports Hebrew glyphs and has the same basic width/height as the Roboto Condensed font. You can then make a separate fontset for that font and I can include it in the skin.

**Comment by dhead666** [comment]
@freak4pc , I don't plan to seek this further. last year I reviewed the fonts that included in the available skins and I counted over 100 different fonts, personally I don't want to keep tab on changes of fonts in skins.

What I do want to achieve is to get kodi to load missing glyphs from default fonts but my cpp voodoo still has a long way to go.

**Comment by freak4pc** [comment]
Thanks both. 
@BigNoid how would I go ahead and tackle that? I'm not sure how to make a new fontset. 

Thanks
Shai

**Comment by bryanbrazil** [comment]
@freak4pc 

Check out Mimic skin's default font set. It uses the webly sleek font and supports Hebrew characters. Since Mimic started out as a Aeon Nox mod, most of the font names are the same and it shouldn't be too difficult to adjust for AN. 

https://github.com/bryanbrazil/skin.mimic/blob/master/1080i/Font.xml
