### ISSUE TITLE
Accessing the audio settings menu during playback

### ISSUE THREAD

**Issue by alexweissman** [BigNoid/Aeon-Nox#650]
This is probably going to sound like a silly question but, how do I access the on-screen audio settings menu during playback?  All I see is a subtitles menu, which tells me that it can't connect to a subtitle server.

But, I just have some local .srt files that I would like to easily turn on and off during playback.  Actually, what I'd really like to do is assign that function to a single button on my MCE remote but...one thing at a time ;-)

**Comment by BigNoid** [comment]
Press menu or OK during playback. Navigate to the audio icon (or press down) and scroll down to the Enalbe subtitles setting. The action you want to map to your remote is called ```ShowSubtitles``` And to flip through the subtitles you need to map ```NextSubtitle``` to your remote.

**Comment by alexweissman** [comment]
Awesome, thanks.  For some reason I wasn't seeing the icons to the left of the play/pause/rewind group.
