### ISSUE TITLE
Custom Fanart Background not showing for TV shows or Films

### ISSUE THREAD

**Issue by ee0u4179** [BigNoid/Aeon-Nox#654]
Selecting "random x fanart" for tv shows and films does not seem to work.

(Music fanart works fine).

I installed using the native Openelec "get more" on the skins page. (Openelec v5.0.1 - Kodi v14.1)

**Comment by BigNoid** [comment]
Works fine here. Debug log will show whats wrong.

**Comment by ee0u4179** [comment]
Hi mate,

Can't find anything offensive in the logs. What exactly am I looking for though? I'm in kodi.log is that right? (I've got debug mode on)

**Comment by ee0u4179** [comment]
OK - I managed to work this out.

I got it to work if you set item background through the *setting up the aeon NOx main menu*. 

It didn't work for me when setting through the *setup background images* item on the general tab.

So manages to get this working but still might be worth looking at?
