### ISSUE TITLE
Are widget context menus used anywhere?

### ISSUE THREAD

**Issue by bryanbrazil** [BigNoid/Aeon-Nox#655]
Just curious, are widget context menus working/available? I can't tell that they work and I don't see anything calling window 1117. Thought maybe this xml is an orphan...

https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/custom_1117_WidgetContextMenu.xml

**Comment by BigNoid** [comment]
Nope, thats just test code. I never bothered with removing it and hope to use it sometime when core supports it.

**Comment by bryanbrazil** [comment]
Ah, got it, thanks!
