### ISSUE TITLE
Character encoding (UTF8)

### ISSUE THREAD

**Issue by Flauschbaellchen** [BigNoid/Aeon-Nox#658]
Hi there,
I hope that's the right spot to report an issue I'm currently facing... The thread within the kodi-forum as well as the google-code page looked a bit abandoned.

I'm using Kodi 14.1 and Aeon Nox 5.5.6 on ArchLinux.
When using this skin Kodi is not able to display utf-8 encoded characters, e.g. japanese ones.
Instead, nothing (blank space) is displayed - no "?" or squares.

When using the standard skin of Kodi (Confluence) I'm able to set the font to "Arial-Based" and everything works fine.
In Aeon Nox the font selection within the settings dialog is disabled and set to "Skin default" which doesn't work.

Is there a way to fix this?
Kind regards.

**Comment by BigNoid** [comment]
You would have to find a version of the roboto font that includes those characters and replace it in the fonts folder. An Arial fontset looks horrible in this skin, as it is designed for a condensed font which is not included in the Kodi app.

**Comment by Flauschbaellchen** [comment]
Closing this issue is misleading. "wont-fix" would be better.
A fix would be to either let users again choose a different font - even if it looks "horrible" (which is a personal taste). it would be still better than to see nothing at all.
Or to provide an own font and contribute it along with the theme.
Currently, the theme is useless for any non-latin languages/files.

**Comment by BigNoid** [comment]
Horrible is not a personal taste in this case. It means that with a non-condensed font textboxes have cut-off text, lists will have overflowing labels etc. I have very carefully selected a free to use condensed font and designed the whole skin with that font. By using arial all that work is diminished imo.
