### ISSUE TITLE
Video playlists background randomization does not work

### ISSUE THREAD

**Issue by flaterichd** [BigNoid/Aeon-Nox#661]
Hi,

Basically if I use "Set item background" for a main menu item, and choose "Video playlists" as background source, and then choose a smart plalist with sort option set to "random", the background fanart images are still shown in order. It seems that is alphabetical movie order.

It would be great if fanart from XSP playlist was shown in random order, as it works for generic "Random movie fanart" or "Random series fanart". Currently pretty much the same images appear every time.

Thanks

P.S. XBMC 13.2, Aeon Nox 5.1.5

**Comment by Trent306** [comment]
Make sure the Group by setting for the playlist is set to Default. This
feature is working for me.

**Comment by flaterichd** [comment]
That does work, thanks! Weird that it doesn't work without grouping by sets...
