### ISSUE TITLE
pvr

### ISSUE THREAD

**Issue by rome1983** [BigNoid/Aeon-Nox#680]
Would it possible to atsc sub-channel support? 4.1 4.2

**Comment by BigNoid** [comment]
I think this is already in master since I merged @manijak PVR section, but not entirely sure about that.

**Comment by rome1983** [comment]
Thanks for the reply,  I tried it earlier its not.

**Comment by manijak** [comment]
I will look into this

**Comment by rome1983** [comment]
Confluence uses ListItem.ChannelNumberLabel instead of ListItem.ChannelNumber.
