### ISSUE TITLE
 Backgrounds bug ?

### ISSUE THREAD

**Issue by Neogrey** [BigNoid/Aeon-Nox#687]
I’m not sure is this a bug or a new feature, but after updating to latest Aeon Nox (master build) the background does not change back.

select addons :
![screenshot002](https://cloud.githubusercontent.com/assets/10816058/13033651/83e0c0f6-d31f-11e5-8a72-0b04f74810c1.png)

![screenshot003](https://cloud.githubusercontent.com/assets/10816058/13033654/93cdc20c-d31f-11e5-9709-f3987a20affd.png)

still the background from the addon:
![screenshot004](https://cloud.githubusercontent.com/assets/10816058/13033664/aef4cd64-d31f-11e5-93ae-189d9d5e18c1.png)

**Comment by BigNoid** [comment]
Should be fixed now, thx.
