### ISSUE TITLE
Blank screen on Conditional Weather

### ISSUE THREAD

**Issue by arieltools** [BigNoid/Aeon-Nox#694]
On selecting Conditional Weather for  the menu entries, the screen shows blank. Where should I start to send you any information about this?

**Comment by BigNoid** [comment]
Did you set the backgrounds up in the weather window?

**Comment by arieltools** [comment]
Weather window shows the standard background.

**Comment by BigNoid** [comment]
Ah so its not setup yet. Go to sideblade and select "background" option to download and enable a weather pack.

**Comment by arieltools** [comment]
Yep. working now. Thanks for the info and the super-fast answer - couldn't
find this setup step anywhere.
