### ISSUE TITLE
Impossible to change the background of Profiles section

### ISSUE THREAD

**Issue by pavelxdd** [BigNoid/Aeon-Nox#698]
I have a custom background on System section, and all its subsections use this background as well. But when I go to System->Profiles the background is set to default and it's impossible to change it (there's no sidebar on this page). Maybe the Profiles section should also use the same background as on the System section?
Thanks.

**Comment by pavelxdd** [comment]
Hello. This issue still persists on Krypton.

**Comment by BigNoid** [comment]
Yup, can confirm the issue. Had profiles mixed up with profile settings. Should be good now.
