### ISSUE TITLE
Rating displayed despite the enabled option to hide ratings in list views.

### ISSUE THREAD

**Issue by pavelxdd** [BigNoid/Aeon-Nox#699]
I have a 'Hide ratings in list views' option enabled, but ratings are still shown in these sections (List view, Sorting by title):

With 'slim list' enabled:
- Videos -> Movies
- Videos -> TV Shows -> _any tv show_ -> list of episodes
- Videos -> Recently added movies
- Videos -> Recently added episodes

With 'slim list' disabled:
- Videos -> TV Shows -> _any tv show_ -> list of episodes
- Videos -> Recently added episodes

**Comment by Tyrindor** [comment]
Same issue, please fix. I do not like seeing episode rating.

**Comment by BigNoid** [comment]
Should be fixed now
