### ISSUE TITLE
Video playlist background not displaying in random order

### ISSUE THREAD

**Issue by cheesechick** [BigNoid/Aeon-Nox#705]
I'm having an issue where I have a home page item set to a smart playlist as its background, but the backgrounds rotate through in alphabetical order, rather than randomly.

This is on Jarvis on Windows 10.

**Comment by BigNoid** [comment]
You can set the sort order to ```random``` in the playlist editor. Than when browsing the playlist you can set the sort order to whatever you like and it won't affect the sort order of the home background playlist.
