### ISSUE TITLE
French MPAA

### ISSUE THREAD

**Issue by Philmo67** [BigNoid/Aeon-Nox#706]
Hello,

Thank you very much for your great work on this skin !

I noticed a small issue regarding the french Mpaa flags.
Using the universal scraper and Imdb french Mpaa ratings, only "10", "12" "16" and "18" are retrieved from Imdb.
According to the variables.xml file, in order to display the CSA flags I put "France:-" as a prefix, to match 10, 12 16 and 18 ratings and the flags are displayed correctly.
The "U" certification doesn't work at all, because the scraper gets "U" (instead of "-U"), "Tout public" or "Tous publics" which doesn't match any condition.
Could you update the variables.xml file ?

**Comment by BigNoid** [comment]
Would be best to remove the ```-``` altogether I think? Will change accordingly.

**Comment by Philmo67** [comment]
Thank you !
