### ISSUE TITLE
Hebrew language not working on OpenELEC \ LibreELEC

### ISSUE THREAD

**Issue by ronassa** [BigNoid/Aeon-Nox#713]
When switching to Hebrew main menu and all Hebrew text shows somthing like that "[] [] []"

**Comment by BigNoid** [comment]
There's an NoTo font set which should work with Hebrew

**Comment by ronassa** [comment]
When I tried that the main menu completely disappears

**Comment by ronassa** [comment]
Just figured it out. it was hard to change the font since I cloudn't read the menu but I did it, now it's working.

**Comment by BigNoid** [comment]
The main menu font is the same font as everything else, at least on master (Krypton) in the noto font.

**Comment by BigNoid** [comment]
Yeah that's a problem indeed. Glad you got it figured out.
