### ISSUE TITLE
Submenu is missing

### ISSUE THREAD

**Issue by Neogrey** [BigNoid/Aeon-Nox#718]
After updating to the current Milhouse build (#1215)+Aeon Nox Master the submenu is missing:
![screenshot001](https://cloud.githubusercontent.com/assets/10816058/21287124/f09c8f36-c464-11e6-90fb-86b2ba728001.png)

**Comment by BigNoid** [comment]
Update [script.skinshortcuts](https://github.com/BigNoid/script.skinshortcuts) to resolve this issue.
Nice background btw 👍

**Comment by Neogrey** [comment]
Haha thanks :D , updating skinshortcuts was the solution.
