### ISSUE TITLE
Invalid syntax in Settings.xml (Krypton)

### ISSUE THREAD

**Issue by Rechi** [BigNoid/Aeon-Nox#729]
Please fix the invalid syntax introduced by https://github.com/BigNoid/Aeon-Nox/commit/1ad9299f43031b0be10c2dfdbb582f4e0eef757d also for Krypton.

**Comment by BigNoid** [comment]
Fixed with https://github.com/BigNoid/Aeon-Nox/commit/f611ced74f682598346ae81ba146f6094c86e027
Will update to repo also.
