### ISSUE TITLE
FEATURE REQUEST - Additional Video Info

### ISSUE THREAD

**Issue by qazero** [BigNoid/Aeon-Nox#730]
Firstly, I love your skin! Secondly, is there any chance you can add an additional layout for the video info when selecting a movie similar to the screenshot below? Thanks

![image](https://cloud.githubusercontent.com/assets/10906010/24811963/75fad8b4-1b85-11e7-97a0-2d691a6caaea.png)

**Comment by BigNoid** [comment]
Sorry, I won't add that. Silvo mod is just for that.
