### ISSUE TITLE
Don't dim down unselected posters

### ISSUE THREAD

**Issue by Tyrindor** [BigNoid/Aeon-Nox#735]
I'd like Aeon Nox to stop dimming down unselected posters in wall views. I'd rather they all be the same brightness.

Can a setting be added for this?

**Comment by BigNoid** [comment]
I won't add a setting for that, but it's quite easy to mod that if you want.
Just remove this control or set the colordiffuse to ```00FFFFFF```
Wall:
https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_503_Wall.xml#L52
Icons:
https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_500_Wall.xml#L26
InfoWall:
https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_51_InfoWall.xml#L70
BannerWall:
https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_58_BannerWall.xml#L85

**Comment by mimbo757** [comment]
> I won't add a setting for that, but it's quite easy to mod that if you want.
> Just remove this control or set the colordiffuse to `00FFFFFF`
> Wall:
> https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_503_Wall.xml#L52
> Icons:
> https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_500_Wall.xml#L26
> InfoWall:
> https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_51_InfoWall.xml#L70
> BannerWall:
> https://github.com/BigNoid/Aeon-Nox/blob/master/1080i/View_58_BannerWall.xml#L85

It possible to do this in Fullscreen wall view as well? Using on openpht and got it resolved in the standard wall, but not the fullscreen. Thanks.
