### ISSUE TITLE
Running 17.3 Krypton

### ISSUE THREAD

**Issue by W4CROBSTER** [BigNoid/Aeon-Nox#736]
How do u access the Addons / Install From Repository, Install from Zip while using Aeon Nox 6.0.1?   i have to change to the default skin then do everything there then swap skins again.  Am i missing something?
Thanks

**Comment by BigNoid** [comment]
It's been removed from the settings window. It's still in the default System submenu.
Apps section has been revamped for v17. If you removed that section, please enable it and you will have a shortcut to the addonbrowser in that section (which is where the install from zip file function is)
