### ISSUE TITLE
Skin stopped working for Kodi v18 Leia RC5

### ISSUE THREAD

**Issue by td75** [BigNoid/Aeon-Nox#762]
The dependency on xbmc.gui version 5.13.0 could not be satisfied.

**Comment by zag2me** [comment]
Need to update the Addon.xml file

<import addon="xbmc.gui" version="5.13.0"/>

to

<import addon="xbmc.gui" version="5.14.0"/>

**Comment by BigNoid** [comment]
Fixed with https://github.com/BigNoid/Aeon-Nox/commit/75eee0b14c8a6f848225afe54f1d8db5c87b943e
Will update the skin on repo as soon as I can, hopefully before final release.
